when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, pull_request]
services:
  database-mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306
  database-pgsql:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=test
    ports:
      - 5432
steps:
  prepare_mysql_database:
    image: mysql
    commands:
      - test/prepare_mysql.sh
  prepare_postgresql_database:
    image: postgres
    commands:
      - test/prepare_postgresql.sh
    environment:
      - PGPASSWORD=example
  build-test-pureftpd-authd-plugin:
    image: golang:1.21.5
    commands:
      - ./build.sh
  test-authentication:
    image: golang:1.21.5
    commands:
      - test/test_pgsql_pw.sh
      - test/test_mysql_pw.sh