when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: [pull_request]
services:
  database-mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306
  database-pgsql:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=test
    ports:
      - 5432
steps:
  prepare_mysql_database:
    group: test_prep
    image: mysql
    commands:
      - test/prepare_mysql.sh
  prepare_postgresql_database:
    group: test_prep
    image: postgres
    commands:
      - test/prepare_postgresql.sh
    environment:
      - PGPASSWORD=example
  build-test-pureftpd-authd-plugin_x86_64:
    group: test_prep
    image: golang:1.21.5
    environment:
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - mkdir -p ./out
      - go mod tidy
      - go build -o "./out/verify_pw_${GOARCH}" verify_pw.go
  build-test-pureftpd-authd-plugin_x86:
    group: test_prep
    image: golang:1.21.5
    environment:
      - GOOS=linux
      - GOARCH=386
    commands:
      - mkdir -p ./out
      - go mod tidy
      - go build -o "./out/verify_pw_${GOARCH}" verify_pw.go
  build-test-pureftpd-authd-plugin_arm64:
    group: test_prep
    image: golang:1.21.5
    environment:
      - GOOS=linux
      - GOARCH=arm64
    commands:
      - mkdir -p ./out
      - go mod tidy
      - go build -o "./out/verify_pw_${GOARCH}" verify_pw.go
  build-test-pureftpd-authd-plugin_arm:
    group: test_prep
    image: golang:1.21.5
    environment:
      - GOOS=linux
      - GOARCH=arm
    commands:
      - mkdir -p ./out
      - go mod tidy
      - go build -o "./out/verify_pw_${GOARCH}" verify_pw.go
  test-authentication-pgsql:
    group: test_auth
    image: golang:1.21.5
    commands:
      - test/test_pgsql_pw.sh
  test-authentication-mysql:
    group: test_auth
    image: golang:1.21.5
    commands:
      - test/test_mysql_pw.sh