services:
  database_mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
  database_pgsql:
    image: postgres
    environment:
      - MYSQL_DATABASE=test
      - POSTGRES_PASSWORD=example
steps:
  build-test-pureftpd-authd-plugin:
    image: golang:1.21.5
    commands:
      - ./build.sh
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: [pull_request, push]