services:
  database-mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306
  database-pgsql:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=test
    ports:
      - 5432
steps:
  prepare_postgresql_database:
    image: postgres
    commands:
      - env | grep PORT_5432_TCP_ADDR | cut -d "=" -f 2
      - echo "connecting to ${psql_host}"
      - psql -h ${psql_host} -d test -p 5432 -U test -f ./sql/prep_psql.sql
    environment:
      - PGPASSWORD=example
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: [pull_request, push]
  build-test-pureftpd-authd-plugin:
    image: golang:1.21.5
    commands:
      - ./build.sh
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: [pull_request, push]